OTEL_TRACES_EXPORTER=otlp
OTEL_EXPORTER_OTLP_PROTOCOL=http/protobuf
OTEL_PROPAGATORS=baggage,tracecontext

; Long-running server adjustments
opentelemetry_distro.transaction_span_enabled_cli=false
opentelemetry_distro.inferred_spans_enabled=false
opentelemetry_distro.traces_processor=simple

[PHP]
memory_limit = ${PHP_MEMORY_LIMIT}
